/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWhoToCallRouteImport } from './routes/_authenticated/who-to-call'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToastRouteImport } from './routes/_authenticated/toast'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSquareRouteImport } from './routes/_authenticated/square'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRegionsRouteImport } from './routes/_authenticated/regions'
import { Route as AuthenticatedPnlQtrRouteImport } from './routes/_authenticated/pnl-qtr'
import { Route as AuthenticatedPnlBonusRouteImport } from './routes/_authenticated/pnl-bonus'
import { Route as AuthenticatedPnlRouteImport } from './routes/_authenticated/pnl'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedDessertsRouteImport } from './routes/_authenticated/desserts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWhoToCallRoute = AuthenticatedWhoToCallRouteImport.update({
  id: '/who-to-call',
  path: '/who-to-call',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToastRoute = AuthenticatedToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSquareRoute = AuthenticatedSquareRouteImport.update({
  id: '/square',
  path: '/square',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegionsRoute = AuthenticatedRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPnlQtrRoute = AuthenticatedPnlQtrRouteImport.update({
  id: '/pnl-qtr',
  path: '/pnl-qtr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPnlBonusRoute = AuthenticatedPnlBonusRouteImport.update({
  id: '/pnl-bonus',
  path: '/pnl-bonus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPnlRoute = AuthenticatedPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDessertsRoute = AuthenticatedDessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desserts': typeof AuthenticatedDessertsRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/regions': typeof AuthenticatedRegionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/square': typeof AuthenticatedSquareRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/toast': typeof AuthenticatedToastRoute
  '/users': typeof AuthenticatedUsersRoute
  '/who-to-call': typeof AuthenticatedWhoToCallRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desserts': typeof AuthenticatedDessertsRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/regions': typeof AuthenticatedRegionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/square': typeof AuthenticatedSquareRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/toast': typeof AuthenticatedToastRoute
  '/users': typeof AuthenticatedUsersRoute
  '/who-to-call': typeof AuthenticatedWhoToCallRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desserts': typeof AuthenticatedDessertsRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/pnl': typeof AuthenticatedPnlRoute
  '/_authenticated/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/_authenticated/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/_authenticated/regions': typeof AuthenticatedRegionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/square': typeof AuthenticatedSquareRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/toast': typeof AuthenticatedToastRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/who-to-call': typeof AuthenticatedWhoToCallRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/desserts'
    | '/locations'
    | '/permissions'
    | '/pnl'
    | '/pnl-bonus'
    | '/pnl-qtr'
    | '/regions'
    | '/settings'
    | '/square'
    | '/targets'
    | '/toast'
    | '/users'
    | '/who-to-call'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/desserts'
    | '/locations'
    | '/permissions'
    | '/pnl'
    | '/pnl-bonus'
    | '/pnl-qtr'
    | '/regions'
    | '/settings'
    | '/square'
    | '/targets'
    | '/toast'
    | '/users'
    | '/who-to-call'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/desserts'
    | '/_authenticated/locations'
    | '/_authenticated/permissions'
    | '/_authenticated/pnl'
    | '/_authenticated/pnl-bonus'
    | '/_authenticated/pnl-qtr'
    | '/_authenticated/regions'
    | '/_authenticated/settings'
    | '/_authenticated/square'
    | '/_authenticated/targets'
    | '/_authenticated/toast'
    | '/_authenticated/users'
    | '/_authenticated/who-to-call'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/who-to-call': {
      id: '/_authenticated/who-to-call'
      path: '/who-to-call'
      fullPath: '/who-to-call'
      preLoaderRoute: typeof AuthenticatedWhoToCallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/toast': {
      id: '/_authenticated/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof AuthenticatedToastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/square': {
      id: '/_authenticated/square'
      path: '/square'
      fullPath: '/square'
      preLoaderRoute: typeof AuthenticatedSquareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/regions': {
      id: '/_authenticated/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof AuthenticatedRegionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pnl-qtr': {
      id: '/_authenticated/pnl-qtr'
      path: '/pnl-qtr'
      fullPath: '/pnl-qtr'
      preLoaderRoute: typeof AuthenticatedPnlQtrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pnl-bonus': {
      id: '/_authenticated/pnl-bonus'
      path: '/pnl-bonus'
      fullPath: '/pnl-bonus'
      preLoaderRoute: typeof AuthenticatedPnlBonusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pnl': {
      id: '/_authenticated/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof AuthenticatedPnlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/desserts': {
      id: '/_authenticated/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof AuthenticatedDessertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDessertsRoute: typeof AuthenticatedDessertsRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPnlRoute: typeof AuthenticatedPnlRoute
  AuthenticatedPnlBonusRoute: typeof AuthenticatedPnlBonusRoute
  AuthenticatedPnlQtrRoute: typeof AuthenticatedPnlQtrRoute
  AuthenticatedRegionsRoute: typeof AuthenticatedRegionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSquareRoute: typeof AuthenticatedSquareRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedToastRoute: typeof AuthenticatedToastRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWhoToCallRoute: typeof AuthenticatedWhoToCallRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDessertsRoute: AuthenticatedDessertsRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPnlRoute: AuthenticatedPnlRoute,
  AuthenticatedPnlBonusRoute: AuthenticatedPnlBonusRoute,
  AuthenticatedPnlQtrRoute: AuthenticatedPnlQtrRoute,
  AuthenticatedRegionsRoute: AuthenticatedRegionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSquareRoute: AuthenticatedSquareRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedToastRoute: AuthenticatedToastRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWhoToCallRoute: AuthenticatedWhoToCallRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
